### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sumeetjain** [ioscowboi/slanguage#1]
:+1:

But here are some things you can think about for taking it to the next level:

---

https://github.com/ioscowboi/slanguage/blob/master/models/answer.rb#L19

Typo!

---

https://github.com/ioscowboi/slanguage/blob/master/models/answer.rb#L32

What kind of objects? Better to be descriptive.

---

https://github.com/ioscowboi/slanguage/blob/master/models/answer.rb#L66-L72

I see this block of code a lot. Any way to DRY things up?

---

https://github.com/ioscowboi/slanguage/blob/master/models/director.rb

You've got controller code (i.e. code that belongs in route handlers) in your model here. Which pieces of code do you think I'm referring to?

---

https://github.com/ioscowboi/slanguage/blob/master/controllers/game.rb

There's a lot of attributes about the game here. Like this stuff: https://github.com/ioscowboi/slanguage/blob/master/controllers/game.rb#L132-L134

How would it change/improve things if you had a `Game` class? Not even necessarily a table/model for it – just a class for organizing methods related to the game's operations.

**Comment by ioscowboi** [comment]
in order (top to bottom) : 

--Typo fixed (hopefully) ,

--Objects described better, 

--I just tried making this less repetitive but it didn't work for me. Should I use a class method and pass in the results as an argument? e.g.: 
  def self.results_as_objects(results) or def results_as_objects(results)
    results_as_objects = []

```
results.each do |r|
   results_as_objects << self.new(r)
end

results_as_objects
```

  end

  ^^This didn't work for me. It says "nomethod error" for both. 

--Yes, I see what you're saying there.  The director.rb didn't work out for me. I think I'm just going to delete that file because I abandoned it. 

--Andrew explained this to me on Monday, but I couldn't get it working between yesterday and today. Let me take another swing at it...
